import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  var array = ['creando', 'aprendiendo', 'estudiando'];
  var interval = 1000; // how much time should the delay between two iterations be (in milliseconds)?
  var promise = Promise.resolve();

  const [word, setWord] = useState('')
  function doSetTimeout(i:string) {
    let timer =setTimeout(function () {
      console.log(i);
      setWord(word+i)
    }, 500);
    ;
    return () => clearTimeout(timer);
}

useEffect(() => {
    for (let i = 0; i < array[0].length; i++){
      // doSetTimeout(array[i])
      setTimeout(() => {
        setWord(array[0].slice(0,i+1));
        console.log(word);
        }, 100 * (i+1));
        // return () => clearTimeout(timer);
    }
  // for (let i = 0; i < array[0].length; i++){
  //     // doSetTimeout(array[i])
  //     setTimeout(() => {
  //       setWord(array[0].slice(0,-1));
  //       console.log(word);
  //       }, 100 * (i+1));
  //       // return () => clearTimeout(timer);
  //   }

}, [array.length]);
  // writeWord('dsadsads')


  return (
    <div className={styles.container}>
      <Head>
        <title>Renzo Damian | Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.nav}>
        <h1 id={styles.logo}>renzo@damian<span id={styles.block}>█</span></h1>
        <ul className={styles.nav_links}>
          <li className={styles.flex_child}>
            Projectos

          </li>
          <li className={styles.flex_child}>
            Acerca de mí

          </li>
          <li className={styles.flex_child}>
            Contáctame

          </li>
        </ul>



      </nav>
      <div className={styles.container}>
        <h2 className={styles.statement}>
          Hola soy Renzo Damian 👋<br />
          Actualmente trabajando en <a href="https://rebels247.com/"> @Rebels247</a><br />
          <span>{word}</span><span id={styles.block}>█</span>nuevas formas de ver la web

        </h2>
      </div>

    </div>
  )
}

export default Home
